# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: mbasso/disl-ci:openjdk-20

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

# before_script:
#   - apt-get update -qq
#   - apt-get install -yqq ant
#   - java -version

build-program:
  stage: build
  script:
    - ant -buildfile BlitzStrike/build.xml compile
    - ant -buildfile BlitzStrike/build.xml jar
  
test-program:
  stage: test
  script:
    - ant -buildfile BlitzStrike/build.xml test

deploy-program:
  stage: deploy
  script:
    - ant -buildfile BlitzStrike/build.xml deploy
  artifacts:
    paths:
      - dist/*.jar
    expire_in: 3 days

  


# junit_setup:
#   stage: build 
#   image: tudorfil9/junit_kata_v1
#   sc
    

# test-program:
#   stage: test
#   # services:
#   #   - name: tudorfil9/junit_kata_v1
#   script:
#     - apk add junit
#     - ant -buildfile BlitzStrike/build.xml compile-test
#     - ant -buildfile BlitzStrike/build.xml test


