image: mbasso/disl-ci:openjdk-20

stages:
  - build
  - deploy

build-program:
  stage: build
  script:
    - ant -buildfile BlitzStrike/build.xml compile
    - ant -buildfile BlitzStrike/build.xml jar
  
deploy-program:
  stage: deploy
  script:
    - ant -buildfile BlitzStrike/build.xml deploy
  artifacts:
    paths:
      - dist/*.jar
    expire_in: 3 days

# test-program:
#   stage: test
#   script:
#     - apk add junit
#     - ant -buildfile BlitzStrike/build.xml test
